# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  port: 5432
  database: ss_rails_dev
  host: localhost
  pool: 5
  username: postgres
  password: S_c193728465

test:
  adapter: postgresql
  encoding: unicode
  port: 5432
  database: ss_rails_test
  host: localhost
  pool: 5
  username: postgres
  password: S_c193728465
